version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: priceline
    container_name: priceline-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/priceline.ini:/usr/local/etc/php/conf.d/priceline.ini
    networks:
      - priceline
  db:
    image: mysql:5.7
    container_name: priceline-db
    restart: unless-stopped
    tty: true
    ports:
      - 3401:3306
    environment:
      MYSQL_DATABASE: priceline_db
      MYSQL_ROOT_PASSWORD: L0V4dGVybmFsU@!_FZGl0LzEyMjUy0
      MYSQL_PASSWORD: jfvdc2y5wsYPHyrJaWHc!
      MYSQL_USER: priceline_user
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - priceline

  nginx:
    image: nginx:alpine
    container_name: priceline-nginx
    restart: unless-stopped
    ports:
      - 8002:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - priceline

networks:
  priceline:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
